### ISSUE TITLE
Not showing appropriate stack trace or file location with Rails 5.1

### ISSUE THREAD

**Issue by niedfelj** [charliesome/better_errors#371]
Not sure what's going on here, but an example putting <%= hi %> in a template in 5.0:

<img width="1433" alt="screen shot 2017-05-01 at 3 33 17 pm" src="https://cloud.githubusercontent.com/assets/294487/25592278/2f6cbb56-2e86-11e7-86a7-e4c446231908.png">

And in 5.1:

<img width="1431" alt="screen shot 2017-05-01 at 3 32 19 pm" src="https://cloud.githubusercontent.com/assets/294487/25592283/3836b5e8-2e86-11e7-9005-1e6e5ca103ed.png">

**Comment by niedfelj** [comment]
It seems to be limited to errors in templates/render code

**Comment by niedfelj** [comment]
@charliesome Are you still maintaining this?

**Comment by kobaltz** [comment]
I noticed this as well and confirmed it's still an issue in Ruby on Rails 5.1.1

**Comment by niedfelj** [comment]
@kobaltz I was going to try to fix this today, and then when I did a checkout and local bundle config, it started working...very strange, but I've tested in a new rails 5.1.1 project in addition and switched back and forth between published gem and the git/master branch and can confirm that using the git method in the Gemfile seems to make it work. Can you confirm also?

```
  gem 'binding_of_caller'
  gem 'better_errors', git: 'https://github.com/charliesome/better_errors.git', branch: 'master'
```

I even tried using the published better_errors.gemspec for 2.1.1 in a local checkout (that was the only file that was different) and it still worked, so maybe this is a bundler issue?

Here's my local setup:

ruby 2.4.1
rails 5.1.1
bundler 1.14.6
rubygems 2.6.11
mac os 10.12.4

**Comment by kobaltz** [comment]
@niedfelj It did work with the `https://github.com/charliesome/better_errors` source. Thanks.

**Comment by dsfernandobond** [comment]
Had the same problem, using https://github.com/charliesome/better_errors fixed it for me too thanks.

**Comment by inopinatus** [comment]
Thanks! This was making debugging of partials really painful.

**Comment by rept** [comment]
Working now with master branch!

**Comment by RobinDaugherty** [comment]
Sounds like this was fixed by #354. New release of the gem will be coming soon.

**Comment by RobinDaugherty** [comment]
Version 2.2.0 of the gem has been released, so this issue seems to be fixed.

**Comment by paneq** [comment]
Not fixed for me unfortunately :(

* rails 5.0.6
* ruby 2.5.1p57

**Comment by RobinDaugherty** [comment]
@paneq @golddiga this issue was for Rails 5.1. Rails 5.0 hasn't had this issue reported. But in my testing with Rails 5.0.6 on Ruby 2.5.1 and an ERB template, I'm getting the correct location. Can you open a new issue with some more information on how to reproduce your issue?
